#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : yaml-cpp
Version  : 0.6.2
Release  : 13
URL      : https://github.com/jbeder/yaml-cpp/archive/yaml-cpp-0.6.2.tar.gz
Source0  : https://github.com/jbeder/yaml-cpp/archive/yaml-cpp-0.6.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause MIT
Requires: yaml-cpp-lib = %{version}-%{release}
Requires: yaml-cpp-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : glibc-dev
BuildRequires : python3
Patch1: yaml-cpp-CVE-2017-5950.patch
Patch2: yaml-cpp-fix-pie.patch

%description
The Google Mock class generator is an application that is part of cppclean.
visit http://code.google.com/p/cppclean/

%package dev
Summary: dev components for the yaml-cpp package.
Group: Development
Requires: yaml-cpp-lib = %{version}-%{release}
Provides: yaml-cpp-devel = %{version}-%{release}

%description dev
dev components for the yaml-cpp package.


%package lib
Summary: lib components for the yaml-cpp package.
Group: Libraries
Requires: yaml-cpp-license = %{version}-%{release}

%description lib
lib components for the yaml-cpp package.


%package license
Summary: license components for the yaml-cpp package.
Group: Default

%description license
license components for the yaml-cpp package.


%prep
%setup -q -n yaml-cpp-yaml-cpp-0.6.2
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1542655066
mkdir -p clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags} VERBOSE=1
popd

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test

%install
export SOURCE_DATE_EPOCH=1542655066
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/yaml-cpp
cp LICENSE %{buildroot}/usr/share/package-licenses/yaml-cpp/LICENSE
cp test/gtest-1.8.0/googlemock/LICENSE %{buildroot}/usr/share/package-licenses/yaml-cpp/test_gtest-1.8.0_googlemock_LICENSE
cp test/gtest-1.8.0/googlemock/scripts/generator/LICENSE %{buildroot}/usr/share/package-licenses/yaml-cpp/test_gtest-1.8.0_googlemock_scripts_generator_LICENSE
cp test/gtest-1.8.0/googletest/LICENSE %{buildroot}/usr/share/package-licenses/yaml-cpp/test_gtest-1.8.0_googletest_LICENSE
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
%exclude /usr/include/gmock/gmock-actions.h
%exclude /usr/include/gmock/gmock-cardinalities.h
%exclude /usr/include/gmock/gmock-generated-actions.h
%exclude /usr/include/gmock/gmock-generated-actions.h.pump
%exclude /usr/include/gmock/gmock-generated-function-mockers.h
%exclude /usr/include/gmock/gmock-generated-function-mockers.h.pump
%exclude /usr/include/gmock/gmock-generated-matchers.h
%exclude /usr/include/gmock/gmock-generated-matchers.h.pump
%exclude /usr/include/gmock/gmock-generated-nice-strict.h
%exclude /usr/include/gmock/gmock-generated-nice-strict.h.pump
%exclude /usr/include/gmock/gmock-matchers.h
%exclude /usr/include/gmock/gmock-more-actions.h
%exclude /usr/include/gmock/gmock-more-matchers.h
%exclude /usr/include/gmock/gmock-spec-builders.h
%exclude /usr/include/gmock/gmock.h
%exclude /usr/include/gmock/internal/custom/gmock-generated-actions.h
%exclude /usr/include/gmock/internal/custom/gmock-generated-actions.h.pump
%exclude /usr/include/gmock/internal/custom/gmock-matchers.h
%exclude /usr/include/gmock/internal/custom/gmock-port.h
%exclude /usr/include/gmock/internal/gmock-generated-internal-utils.h
%exclude /usr/include/gmock/internal/gmock-generated-internal-utils.h.pump
%exclude /usr/include/gmock/internal/gmock-internal-utils.h
%exclude /usr/include/gmock/internal/gmock-port.h
%exclude /usr/include/gtest/gtest-death-test.h
%exclude /usr/include/gtest/gtest-message.h
%exclude /usr/include/gtest/gtest-param-test.h
%exclude /usr/include/gtest/gtest-param-test.h.pump
%exclude /usr/include/gtest/gtest-printers.h
%exclude /usr/include/gtest/gtest-spi.h
%exclude /usr/include/gtest/gtest-test-part.h
%exclude /usr/include/gtest/gtest-typed-test.h
%exclude /usr/include/gtest/gtest.h
%exclude /usr/include/gtest/gtest_pred_impl.h
%exclude /usr/include/gtest/gtest_prod.h
%exclude /usr/include/gtest/internal/custom/gtest-port.h
%exclude /usr/include/gtest/internal/custom/gtest-printers.h
%exclude /usr/include/gtest/internal/custom/gtest.h
%exclude /usr/include/gtest/internal/gtest-death-test-internal.h
%exclude /usr/include/gtest/internal/gtest-filepath.h
%exclude /usr/include/gtest/internal/gtest-internal.h
%exclude /usr/include/gtest/internal/gtest-linked_ptr.h
%exclude /usr/include/gtest/internal/gtest-param-util-generated.h
%exclude /usr/include/gtest/internal/gtest-param-util-generated.h.pump
%exclude /usr/include/gtest/internal/gtest-param-util.h
%exclude /usr/include/gtest/internal/gtest-port-arch.h
%exclude /usr/include/gtest/internal/gtest-port.h
%exclude /usr/include/gtest/internal/gtest-string.h
%exclude /usr/include/gtest/internal/gtest-tuple.h
%exclude /usr/include/gtest/internal/gtest-tuple.h.pump
%exclude /usr/include/gtest/internal/gtest-type-util.h
%exclude /usr/include/gtest/internal/gtest-type-util.h.pump
%exclude /usr/lib/libgmock.so
%exclude /usr/lib/libgmock_main.so
%exclude /usr/lib/libgtest.so
%exclude /usr/lib/libgtest_main.so
/usr/include/yaml-cpp/anchor.h
/usr/include/yaml-cpp/binary.h
/usr/include/yaml-cpp/contrib/anchordict.h
/usr/include/yaml-cpp/contrib/graphbuilder.h
/usr/include/yaml-cpp/dll.h
/usr/include/yaml-cpp/emitfromevents.h
/usr/include/yaml-cpp/emitter.h
/usr/include/yaml-cpp/emitterdef.h
/usr/include/yaml-cpp/emittermanip.h
/usr/include/yaml-cpp/emitterstyle.h
/usr/include/yaml-cpp/eventhandler.h
/usr/include/yaml-cpp/exceptions.h
/usr/include/yaml-cpp/mark.h
/usr/include/yaml-cpp/node/convert.h
/usr/include/yaml-cpp/node/detail/bool_type.h
/usr/include/yaml-cpp/node/detail/impl.h
/usr/include/yaml-cpp/node/detail/iterator.h
/usr/include/yaml-cpp/node/detail/iterator_fwd.h
/usr/include/yaml-cpp/node/detail/memory.h
/usr/include/yaml-cpp/node/detail/node.h
/usr/include/yaml-cpp/node/detail/node_data.h
/usr/include/yaml-cpp/node/detail/node_iterator.h
/usr/include/yaml-cpp/node/detail/node_ref.h
/usr/include/yaml-cpp/node/emit.h
/usr/include/yaml-cpp/node/impl.h
/usr/include/yaml-cpp/node/iterator.h
/usr/include/yaml-cpp/node/node.h
/usr/include/yaml-cpp/node/parse.h
/usr/include/yaml-cpp/node/ptr.h
/usr/include/yaml-cpp/node/type.h
/usr/include/yaml-cpp/noncopyable.h
/usr/include/yaml-cpp/null.h
/usr/include/yaml-cpp/ostream_wrapper.h
/usr/include/yaml-cpp/parser.h
/usr/include/yaml-cpp/stlemitter.h
/usr/include/yaml-cpp/traits.h
/usr/include/yaml-cpp/yaml.h
/usr/lib64/cmake/yaml-cpp/yaml-cpp-config-version.cmake
/usr/lib64/cmake/yaml-cpp/yaml-cpp-config.cmake
/usr/lib64/cmake/yaml-cpp/yaml-cpp-targets-relwithdebinfo.cmake
/usr/lib64/cmake/yaml-cpp/yaml-cpp-targets.cmake
/usr/lib64/libyaml-cpp.so
/usr/lib64/pkgconfig/yaml-cpp.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libyaml-cpp.so.0.6
/usr/lib64/libyaml-cpp.so.0.6.2

%files license
%defattr(0644,root,root,0755)
%exclude /usr/share/package-licenses/yaml-cpp/test_gtest-1.8.0_googlemock_LICENSE
%exclude /usr/share/package-licenses/yaml-cpp/test_gtest-1.8.0_googlemock_scripts_generator_LICENSE
%exclude /usr/share/package-licenses/yaml-cpp/test_gtest-1.8.0_googletest_LICENSE
/usr/share/package-licenses/yaml-cpp/LICENSE
